name: Auto-Indexing

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ping-indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Call IndexNow Cron
        env:
          INDEX_NOW_SECRET: ${{ secrets.INDEX_NOW_SECRET }}
        run: |
          curl -X GET "https://inshortbd.com/api/cron/indexnow" \
          -H "Authorization: Bearer $INDEX_NOW_SECRET" \
          --fail
